<?php
$this->headTitle('Add User');
/**
 * @var \Application\Form\PostForm $form
 */
$form = $this->form;

$form->get('email')
    ->setAttribute('class','form-control')
    ->setAttribute('placeholder', 'name@example.com');

$form->get('full_name')
    ->setAttribute('class','form-control')
    ->setAttribute('placeholder', 'John Doe');

$form->get('status')->setAttribute('class', 'form-control');
$form->get('password')->setAttribute('class', 'form-control');

$form->get('confirm_password')->setAttribute('class', 'form-control');
$form->get('submit')
    ->setAttribute('class', 'btn btn-primary');
$form->prepare();
?>

<h1>Add User</h1>
<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?= $this->formRow($form->get('email')); ?>
            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('full_name')); ?>
            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('password')); ?>
            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('confirm_password')); ?>
            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('status')); ?>
            </div>
            <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>