<?php
    $this->headTitle('Change Password');
    $this->mainMenu()->setActiveItem('admin');

    $form->get('old_password')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Enter old password');

    $form->get('new_password')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Enter new password');

    $form->get('confirm_new_password')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Re-enter new password');

    $form->get('submit')
        ->setAttribute('class', 'btn btn-primary');
    $form->prepare();
?>

<h1>Change Password for <?= $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?= $this->formRow($form->get('old_password')); ?>
            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('new_password')); ?>
            </div>
            <div class="form-group">
                <?= $this->formRow($form->get('confirm_new_password')); ?>
            </div>
            <?= $this->formElement($form->get('csrf')); ?>
            <?= $this->formSubmit($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>