<?php
$this->headTitle('Edit User');
$this->mainMenu()->setActiveItem('admin');

/**
 * @var \Application\Form\PostForm $form
 */
$form = $this->form;

$form->get('email')
    ->setAttribute('class','form-control')
    ->setAttribute('placeholder', 'name@example.com');

$form->get('full_name')
    ->setAttribute('class','form-control')
    ->setAttribute('placeholder', 'John Doe');

$form->get('status')->setAttribute('class', 'form-control');
$form->get('submit')
    ->setAttribute('class', 'btn btn-primary')
    ->setValue('save');
$form->prepare();
?>

<h1>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
            <div class="form-group">
                <?= $this->formRow($form->get('email')); ?>
            </div>

            <div class="form-group">
                <?= $this->formRow($form->get('full_name')); ?>
            </div>

            <div class="form-group">
                <?= $this->formRow($form->get('status')); ?>
            </div>
            <?= $this->formSubmit($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
