<?php
    $this->headTitle('Set New Password');

    $form->get('new_password')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Type New Password');

    $form->get('confirm_new_password')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Confirm New Password');

    $form->get('submit')
        ->setAttribute('class', 'btn btn-primary');
    $form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>

            <h2>Set New Password</h2>

            <p>Enter your new password in the form below</p>

            <div class="form-group">
                <?= $this->formRow($form->get('new_password')); ?>
            </div>

            <div class="form-group">
                <?= $this->formRow($form->get('confirm_new_password')); ?>
            </div>

            <?= $this->formElement($form->get('submit')); ?>
            <?= $this->formElement($form->get('csrf')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>