<?php
    /**
     * @var \Application\Form\PostForm $form
     */
    $form = $this->form;

    $form->get('title')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Enter post title here');

    $form->get('content')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Type content here')
        ->setAttribute('rows', 6);

    $form->get('tags')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', 'Enter comma sepated list of tags');

    $form->get('status')
        ->setAttribute('class', 'form-control');

    $form->get('submit')->setAttribute('class', 'btn btn-primary');
    $form->prepare();
?>

<h1>Add New Post</h1>

<p>Please fill out the following form and click the <i>Create</i> button.</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        <div class="form-group">
            <?= $this->formRow($form->get('title')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($form->get('content')); ?>
        </div>
        <div class="form-group">
            <?= $this->formRow($form->get('tags')); ?>
            <p class="help-block">Separate tags with comma.</p>
        </div>
        <div class="form-group">
            <?= $this->formRow($form->get('status')); ?>
        </div>
        <?= $this->formSubmit($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>