<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Kuddelmuddel Blog')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <div class="container">


            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->

                    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                        <div class="container">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                    Kuddelmuddel Blog
                                </a>
                            </div>
                            <div class="collapse navbar-collapse">
                                <ul class="nav navbar-nav">
                                    <?php
                                    // Initialize navbar items
                                    $this->mainMenu()->setItems([
                                        [
                                            'id' => 'myPosts',
                                            'label' => 'My Posts',
                                            'link' => $this->url('posts', ['action' => 'admin'])
                                        ],
                                        [
                                            'id' => 'admin',
                                            'label' => 'Admin',
                                            'link' => $this->url('users')
                                        ],
                                        [
                                            'id' => 'login',
                                            'label' => 'Login',
                                            'link' => $this->url('login')
                                        ],
                                    ]);

                                    echo $this->mainMenu()->render();
                                    ?>

                                </ul>
                            </div>
                        </div>
                    </nav>



                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->

                    <ol class="breadcrumb">
                        <li class="active">Home</li>
                    </ol>

                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <?= $this->content ?>
                </div>
            </div>

            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> by Kuddelmuddel Company. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
